### ISSUE TITLE
GnuCash 3.10 segfaults when editing scheduled transactions

### ISSUE THREAD

**Issue by chenghlee** [chenghlee/gnucash-ppa#1]
Does not happen with the official Flatpak version, so it likely has something to do with how we're building it using older Ubuntu 18.04 libraries.

**Comment by chenghlee** [comment]
Stack trace:
```
#0  0x00007f692b22c1f2 in gdk_window_has_impl (window=<optimized out>) at ../../../../gdk/gdkwindow.c:677
#1  _gdk_window_has_impl (window=window@entry=0x0) at ../../../../gdk/gdkwindow.c:678
#2  0x00007f692b26246e in gdk_x11_window_get_xid (window=0x0) at ../../../../../gdk/x11/gdkwindow-x11.c:5566
#3  0x00007f68f7780f7b in gtk_im_context_xim_filter_keypress (context=0x55c0eca90d70, event=0x55c0ec37bb30) at ../../../../../modules/input/gtkimcontextxim.c:673
#4  0x00007f692d1d7513 in gtk_im_multicontext_filter_keypress (context=0x55c0ecc3fc60, event=0x55c0ec37bb30) at ../../../../gtk/gtkimmulticontext.c:359
#5  0x00007f692bb68319 in ?? () from /usr/lib/x86_64-linux-gnu/gnucash/gnucash/libgncmod-register-gnome.so
#6  0x00007f692d1f78f7 in _gtk_marshal_BOOLEAN__BOXEDv (closure=0x55c0ead2de40, return_value=0x7ffd293b2450, instance=<optimized out>, args=<optimized out>, 
    marshal_data=<optimized out>, n_params=<optimized out>, param_types=0x55c0ead2d720) at ../../../../gtk/gtkmarshalers.c:129
#7  0x00007f692c9e3250 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#8  0x00007f692c9fe3cd in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#9  0x00007f692c9ff12f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#10 0x00007f692d33f534 in gtk_widget_event_internal (widget=widget@entry=0x55c0eb204430, event=event@entry=0x55c0ec37bb30) at ../../../../gtk/gtkwidget.c:7744
#11 0x00007f692d3415aa in gtk_widget_event (widget=widget@entry=0x55c0eb204430, event=event@entry=0x55c0ec37bb30) at ../../../../gtk/gtkwidget.c:7314
#12 0x00007f692d35ff0b in gtk_window_propagate_key_event (window=window@entry=0x55c0ec74d3e0, event=event@entry=0x55c0ec37bb30) at ../../../../gtk/gtkwindow.c:8310
#13 0x00007f692d3638fb in gtk_window_key_press_event (widget=0x55c0ec74d3e0, event=0x55c0ec37bb30) at ../../../../gtk/gtkwindow.c:8343
#14 0x00007f692d1f78f7 in _gtk_marshal_BOOLEAN__BOXEDv (closure=0x55c0ead2de40, return_value=0x7ffd293b2850, instance=<optimized out>, args=<optimized out>, 
    marshal_data=<optimized out>, n_params=<optimized out>, param_types=0x55c0ead2d720) at ../../../../gtk/gtkmarshalers.c:129
#15 0x00007f692c9e3346 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#16 0x00007f692c9fe3cd in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#17 0x00007f692c9ff12f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#18 0x00007f692d33f534 in gtk_widget_event_internal (widget=0x55c0ec74d3e0, event=0x55c0ec37bb30) at ../../../../gtk/gtkwidget.c:7744
#19 0x00007f692d1f493f in propagate_event (widget=0x55c0ec74d3e0, event=0x55c0ec37bb30, captured=<optimized out>, topmost=0x0) at ../../../../gtk/gtkmain.c:2685
#20 0x00007f692d1f6948 in gtk_main_do_event (event=<optimized out>) at ../../../../gtk/gtkmain.c:1915
#21 0x00007f692b21c765 in _gdk_event_emit (event=event@entry=0x55c0ec37bb30) at ../../../../gdk/gdkevents.c:73
#22 0x00007f692b24cf92 in gdk_event_source_dispatch (source=<optimized out>, callback=<optimized out>, user_data=<optimized out>) at ../../../../../gdk/x11/gdkeventsource.c:367
#23 0x00007f692e683417 in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#24 0x00007f692e683650 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#25 0x00007f692e683962 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#26 0x00007f692d1f5a25 in gtk_main () at ../../../../gtk/gtkmain.c:1323
#27 0x00007f692e39b796 in gnc_ui_start_event_loop () from /usr/lib/x86_64-linux-gnu/gnucash/gnucash/libgncmod-gnome-utils.so
#28 0x000055c0e9927982 in ?? ()
#29 0x00007f692e9a31ad in invoke_main_func (body_data=0x7ffd293b3130) at init.c:340
#30 0x00007f692e985a4a in c_body (d=0x7ffd293b3070) at continuations.c:422
#31 0x00007f692ea068ff in vm_regular_engine (thread=0x0, vp=0x55c0eb2f6f30, registers=0x55c0ead11b70, resume=1) at vm-engine.c:784
#32 0x00007f692ea09137 in scm_call_n (proc=proc@entry=0x55c0eb3e4a20, argv=argv@entry=0x0, nargs=nargs@entry=0) at vm.c:1257
#33 0x00007f692e98b639 in scm_call_0 (proc=proc@entry=0x55c0eb3e4a20) at eval.c:481
#34 0x00007f692e9f7da2 in catch (tag=tag@entry=0x404, thunk=0x55c0eb3e4a20, handler=0x55c0eb3e4a00, pre_unwind_handler=0x55c0eb3e49e0) at throw.c:137
#35 0x00007f692e9f8085 in scm_catch_with_pre_unwind_handler (key=key@entry=0x404, thunk=<optimized out>, handler=<optimized out>, pre_unwind_handler=<optimized out>) at throw.c:254
#36 0x00007f692e9f824f in scm_c_catch (tag=tag@entry=0x404, body=body@entry=0x7f692e985a40 <c_body>, body_data=body_data@entry=0x7ffd293b3070, 
    handler=handler@entry=0x7f692e985cd0 <c_handler>, handler_data=handler_data@entry=0x7ffd293b3070, pre_unwind_handler=pre_unwind_handler@entry=0x7f692e985b30 <pre_unwind_handler>, 
    pre_unwind_handler_data=0x55c0eb2f0a20) at throw.c:377
#37 0x00007f692e986030 in scm_i_with_continuation_barrier (body=body@entry=0x7f692e985a40 <c_body>, body_data=body_data@entry=0x7ffd293b3070, 
    handler=handler@entry=0x7f692e985cd0 <c_handler>, handler_data=handler_data@entry=0x7ffd293b3070, pre_unwind_handler=pre_unwind_handler@entry=0x7f692e985b30 <pre_unwind_handler>, 
    pre_unwind_handler_data=0x55c0eb2f0a20) at continuations.c:360
#38 0x00007f692e9860c5 in scm_c_with_continuation_barrier (func=<optimized out>, data=<optimized out>) at continuations.c:456
#39 0x00007f692e9f69ec in with_guile (base=0x7ffd293b30d0, data=0x7ffd293b3100) at threads.c:661
#40 0x00007f692695bc42 in GC_call_with_stack_base () from /usr/lib/x86_64-linux-gnu/libgc.so.1
#41 0x00007f692e9f6d08 in scm_i_with_guile (dynamic_state=<optimized out>, data=data@entry=0x7ffd293b3100, func=func@entry=0x7f692e9a3190 <invoke_main_func>) at threads.c:704
#42 scm_with_guile (func=func@entry=0x7f692e9a3190 <invoke_main_func>, data=data@entry=0x7ffd293b3130) at threads.c:710
#43 0x00007f692e9a3342 in scm_boot_guile (argc=1, argv=0x7ffd293b32b8, main_func=0x55c0e99276f0, closure=0x0) at init.c:323
#44 0x000055c0e9927250 in main ()
```
Quick search suggests this is a known bug: https://bugs.gnucash.org/show_bug.cgi?id=795014
